services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_NOPRUNE=true
  webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ./open-webui:/app/backend/data
    ports:
      - 8080:8080
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
  oi:
    build:
      context: .
      dockerfile: open-interpreter/Dockerfile
    volumes:
      - ./open-interpreter/profiles:/opt/app/open-interpreter/profiles
      - $HOME:$HOME
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
  repo-loader:
    build:
      context: .
      dockerfile: repository-loader/Dockerfile
    volumes:
      - ./repository-loader/work:/work
    tty: true
