#!/bin/bash

if [ -p /dev/stdin ]; then
    input=$(cat -)
elif [ $# -ne 0 ]; then
    input=$(echo $1)
else
    echo "パイプか引数を指定してください。"
    exit 1
fi

MODEL="7shi/gemma-2-jpn-translate:2b-instruct-q8_0"

prompt=$(echo $input | tr -d '\n')

curl -s http://localhost:11434/api/generate \
  -d "$(jq -n --arg model "$MODEL" --arg prompt "Please translate the following content into Japanese: $prompt" '{model: $model, prompt: $prompt}')" | jq -r '.response' | tr -d '\n'
echo
